CREATE TABLE IF NOT EXISTS "spaced-rep_card" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "spaced-rep_card_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"deck_id" integer NOT NULL,
	"question" text NOT NULL,
	"answer" text NOT NULL,
	"last_reviewed" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "spaced-rep_deck" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "spaced-rep_deck_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" varchar(256),
	"name" varchar(256) NOT NULL,
	"description" text,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "spaced-rep_user" (
	"id" varchar(256) PRIMARY KEY NOT NULL,
	"email" varchar(256) NOT NULL,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "spaced-rep_card" ADD CONSTRAINT "spaced-rep_card_deck_id_spaced-rep_deck_id_fk" FOREIGN KEY ("deck_id") REFERENCES "public"."spaced-rep_deck"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "spaced-rep_deck" ADD CONSTRAINT "spaced-rep_deck_user_id_spaced-rep_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."spaced-rep_user"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "flashcard_deck_id_idx" ON "spaced-rep_card" USING btree ("deck_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "deck_name_idx" ON "spaced-rep_deck" USING btree ("name");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "deck_user_id_idx" ON "spaced-rep_deck" USING btree ("user_id");